//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int ProductCategory_Id { get; set; }
        public int ProductCategory_ProdId { get; set; }
        public int ProductCategory_CatId { get; set; }
        public Nullable<System.DateTime> ProductCategory_DeactivateDate { get; set; }
    
        public virtual CategoryLookup CategoryLookup { get; set; }
        public virtual Product Product { get; set; }
    }
}
