//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryLookup
    {
        public CategoryLookup()
        {
            this.ProductCategories = new HashSet<ProductCategory>();
        }
    
        public int CategoryLookup_Id { get; set; }
        public string CategoryLookup_Name { get; set; }
    
        public virtual ICollection<ProductCategory> ProductCategories { get; set; }
    }
}
